server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push


scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    # Map Docker metadata â†’ Loki labels
    relabel_configs:
      # Container name (without leading /)
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      # docker-compose service name (if you use compose)
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

      # stdout / stderr
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

      # Optional: set a consistent job label
      - target_label: 'job'
        replacement: 'docker'

    pipeline_stages:
      - docker: {}     # parses {"log": "...", "stream":..., "time":...}
